using System;
using System.Collections.Generic;
using System.Linq;

namespace APHI.Core.Models;

/// <summary>
/// Represents a full health report generated by the project scanner.
/// </summary>
public class HealthReport
{
    /// <summary>
    /// Name of the scanned project.
    /// </summary>
    public string ProjectName { get; set; } = string.Empty;

    /// <summary>
    /// Path to the scanned project.
    /// </summary>
    public string ProjectPath { get; set; } = string.Empty;

    /// <summary>
    /// Time when the scan started.
    /// </summary>
    public DateTime ScanStartTime { get; set; }

    /// <summary>
    /// Time when the scan finished.
    /// </summary>
    public DateTime ScanEndTime { get; set; }

    /// <summary>
    /// Total duration of the scan.
    /// </summary>
    public TimeSpan ScanDuration => ScanEndTime - ScanStartTime;

    /// <summary>
    /// List of issues found during the scan.
    /// </summary>
    public List<HealthIssue> Issues { get; set; } = new List<HealthIssue>();

    /// <summary>
    /// The overall health score of the project.
    /// </summary>
    public HealthScore HealthScore { get; set; } = new HealthScore();

    /// <summary>
    /// Detailed performance metrics for the project.
    /// </summary>
    public PerformanceMetrics PerformanceScore { get; set; } = new PerformanceMetrics();

    /// <summary>
    /// Total number of maps scanned.
    /// </summary>
    public int TotalMaps { get; set; }

    /// <summary>
    /// Total number of layers scanned.
    /// </summary>
    public int TotalLayers { get; set; }

    /// <summary>
    /// Total number of tables scanned.
    /// </summary>
    public int TotalTables { get; set; }

    /// <summary>
    /// Total number of layouts scanned.
    /// </summary>
    public int TotalLayouts { get; set; }

    /// <summary>
    /// Total number of toolboxes in the project.
    /// </summary>
    public int TotalToolboxes { get; set; }

    /// <summary>
    /// Total number of folder connections in the project.
    /// </summary>
    public int TotalFolderConnections { get; set; }

    /// <summary>
    /// Gets issues filtered by category.
    /// </summary>
    public IEnumerable<HealthIssue> GetIssuesByCategory(IssueCategory category)
    {
        return Issues.Where(i => i.Category == category);
    }

    /// <summary>
    /// Gets issues filtered by severity.
    /// </summary>
    public IEnumerable<HealthIssue> GetIssuesBySeverity(IssueSeverity severity)
    {
        return Issues.Where(i => i.Severity == severity);
    }

    /// <summary>
    /// Gets the count of critical issues.
    /// </summary>
    public int GetCriticalIssueCount()
    {
        return Issues.Count(i => i.Severity == IssueSeverity.Critical);
    }
}
