name: .NET Build and Test

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v4
    
    - name: Setup .NET 8
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 8.0.x
        
    - name: Restore dependencies
      run: dotnet restore src/APHI/APHI.csproj
      
    - name: Build
      run: dotnet build src/APHI/APHI.csproj --configuration Release --no-restore
      
    - name: Test
      run: dotnet test src/APHI/APHI.csproj --no-build --verbosity normal --configuration Release
