name: .NET Build and Test

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: windows-latest

    defaults:
      run:
        working-directory: src

    steps:
    - uses: actions/checkout@v4
    
    - name: Setup .NET 8
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 8.0.x

    - name: Setup MSBuild
      uses: microsoft/setup-msbuild@v2
        
    - name: Restore dependencies
      run: dotnet restore src/APHI/APHI.csproj
      
    - name: Build
      run: msbuild src/APHI/APHI.csproj /p:Configuration=Release
      
    - name: Test
      run: dotnet test src/APHI/APHI.csproj --no-build --verbosity normal --configuration Release
